runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 0.5

env_variables:
  NEXT_PUBLIC_DISCORD_CLIENT_ID: 1441100218656489634
  NEXT_PUBLIC_BASE_URL: "https://serveless-epitech-dev.appspot.com"
  NEXT_PUBLIC_DISCORD_REDIRECT_URI: "https://europe-west6-serveless-epitech-dev.appspot.com/api/auth/discord/callback"
  NEXT_PUBLIC_DISCORD_SECRET: "projects/serveless-epitech-dev/secrets/discord_client_secret/versions/latest"
  NEXT_PUBLIC_GRID_SIZE: 100
  BUCKET_NAME: "example-gcs-bucket"
